### ISSUE TITLE
mustache.properties 无效

### ISSUE THREAD

**Issue by RainNiu** [mjeanroy/springmvc-mustache#4]
Jmustache模式下使用mustache.properties 无效，求助！

**Comment by mjeanroy** [comment]
I'm sorry, I don't speak chinese, can you post your question in english please?

**Comment by RainNiu** [comment]
In 'Jmustache' mode，The  file 'mustache.properties' is not invalided，Please give me a suggestion！Thank s!

**Comment by mjeanroy** [comment]
What do you mean by "not invalides"? Can you give me more details about your use case ?

**Comment by RainNiu** [comment]
The file 'mustache.properties' can't used!

**Comment by mjeanroy** [comment]
Hi,

I will need more details, can you give me the logs (you will have to activate `TRACE` level on `com.github.mjeanroy.springmvc.view.mustache` package)?

As you can see in this [sample project](https://github.com/mjeanroy/springmvc-mustache/tree/master/samples/springmvc-mustache-jmustache), it should works, so I think there's an issue with your configuration:
- Where is your `mustache.properties` file?
- Can you give me your spring configuration?

If you can send me a project reproducing your issue, I'll be able to investiguate, without more details it will be difficult...

**Comment by RainNiu** [comment]
Hi,
Can you give me a suggestion? My web page shows a mess of code！
Please give me your email if it be convenient to yo! Thanks!

**Comment by mjeanroy** [comment]
Hi,

> Can you give me a suggestion?

I already gave you some suggestions:
- Can you give me the logs?
- Where is your `mustache.properties` file?
- Can you give me your spring configuration?

Without more information, I'm blind and I can't help you more, sorry.

> Please give me your email if it be convenient to yo! Thanks!

I prefer discuss your issue here, not by email, as it may helps other.
