### ISSUE TITLE
Unable to render template

### ISSUE THREAD

**Issue by vivekdhiman** [mjeanroy/springmvc-mustache#5]
HI, 

I am getting weird error `com.github.mjeanroy.springmvc.view.mustache.exceptions.MustacheTemplateNotFoundException: Mustache template /templates/home.template.html does not exist
` 

I can see the template is getting create under templates folder as below.

<img width="440" alt="Screen Shot 2020-04-17 at 12 26 44 AM" src="https://user-images.githubusercontent.com/7066652/79538819-575b0080-8042-11ea-8b4b-e4cb71502d35.png">

Have below two dependencies in my pom.xml
<dependency>
			<groupId>com.github.spullara.mustache.java</groupId>
			<artifactId>compiler</artifactId>
			<version>0.9.6</version>
		</dependency>
<dependency>
			<groupId>com.github.mjeanroy</groupId>
			<artifactId>springmvc-mustache</artifactId>
			<version>0.4.0</version>
		</dependency>

Below is my controller

`@Controller
public class HomePageController {
    @GetMapping("/home")
    public ModelAndView homePage(@RequestParam(name="name", required=false, defaultValue="World") String name, Model model) {
        CDAEntry array = DemoApplication.client
                .fetch(CDAEntry.class)
                .one(SystemConstants.CONTENT_TYPE_HOMEPAGE);
        ModelAndMustacheView view = new ModelAndMustacheView("home");
        view.addObject("home", array);
        return view;
    }
}
`

**Comment by mjeanroy** [comment]
Hi, 
Can you give me more details? For example:

- Can you copy the full stack trace?
- Where did you put your templates (`src/main/resources` or `src/main/webapp`?)
- Can you given me the configuration you used?

Thanks.

**Comment by mjeanroy** [comment]
@vivekdhiman Closing the issue since you did not respond, feel free to comment if you still have the problem.
